# 存储位置，不填默认当前目录下download
save_dir: ./download
# 执行过的历史任务存放位置
history_dir: ./history
# 执行日志
log_dir: ./log
log_status: true

# 任务清单
task_list: url.txt
# 任务连续最大错误次数
task_error_max_count: 50
# 错误时候休眠多久后重试
task_error_duration: 1
# 下载任务并发数
concurrency: 5
# m3u8 片段并发大小为总数的十分之一，例：有120各片段，那么并发请求就是12
concurrency_m3u8: 10
# 结束后清空任务列表
task_clear: false
# 使用ffmpeg进行合并分片
use_ffmpeg: true
# ffmpeg程序所在地址
ffmpeg_path: ffmpeg.exe

# 请求头相关
headers:
  user_agent: User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

# 代理地址
proxy: http://127.0.0.1:10809
proxy_status: false
